pipeline {
    agent any
    stages {
        stage('Docker Build and Push') {
            steps {
                script {
                    def backendImage = docker.build("hub.cjblink1.pro/commute-backend:${GIT_COMMIT}")
                    webAppImage.push()
                }
            }
        }
    }
}